bukiin = {
        'sleep':'睡眠',
        'fuyuu':'浮遊特攻',
        'kanasibari': 'かなしばり',
        'kanekui': '金食い攻撃',
        'suisei': '水棲特攻',
        'mukiryoku': '無気力',
        'kamaitati': '正面3方向',
        'konran':'混乱',
        'metubusi': '目つぶし',
        'drain': 'ドレイン特攻',
        'renzoku': '連続攻撃',
        'shokubutu': '植物特攻',
        'kaisin': '会心の一撃',
        'heal': '回復',
        'kinzoku':'金属特攻',
        'dragon':'ドラゴン特攻',
        'yosei':'余勢',
        'honoo':'炎飛ばし',
        'aohonoo':'青炎飛ばし',
        'base8':'基本値+8',
        'hitotume':'1ツ目特攻',
        'hp20':'HP+20',
        'hp15':'HP+15',
        'hp10':'HP+10',
        'hp5':'HP+5',
        'mekki':'サビよけ',
        'fuuin':'封印',
        'magic':'魔法特攻',
        'base3':'基本値+3',
        'bakuhatu':'爆発特攻',
        'tame':'ため攻撃',
        'kyouka':'強化',
        'hp1':'HP1',
        'lvdown':'LVダウン',
        'ooburi':'大振り',
        'kabehori':'壁掘り',
        'wanakowasi':'ワナ壊し',
        'nigefuuji':'逃げ封じ',
        'jakutai':'威力弱体',
        'moroi':'もろい',
}

tatein = {
        'honoo':'炎減少',
        'zeroiti':'一の位防御',
        'bakuhatu':'爆発減少',
        'haramoti':'ハラモチ',
        'yoke':'避けアップ',
        'hiru':'昼強化',
        'magic':'魔法ダメージ',
        'bakuhatumukou':'爆発無効',
        'mekki':'サビよけ',
        'nusumi':'盗み守り',
        'kanekui':'金食い防御',
        'saimin':'催眠無効',
        'base8':'基本値+8',
        'tuibami':'ついばみ守り',
        'base3':'基本値+3',
        'nigiri':'にぎり守り',
        'hp20':'HP+20',
        'hp15':'HP+15',
        'hp10':'HP+10',
        'hp5':'HP+5',
        'damagekeiken':'ダメージ経験',
        'manpukudo':'満腹度回復',
        'shojikin':'所持金守り',
        'counter':'カウンター',
        'lvdown':'LVダウン',
        'kyouka':'強化',
        'wazakaifuku':'技回復',
        'hp1':'HP1',
        'haraheri':'ハラヘリ',
        'ukejakutai':'受け弱体',
        'moroi':'もろい',
        'wanakawasi':'ワナかわし',
        'haraheranai':'腹減らない',
        'ugokazu':'動かず',
        'sutemi':'捨て身',
        'ukenagasi':'受け流し'
}